version: '3'
services:
  database:
    image: mongo:4.2
    expose:
      - "27017"
      - "37017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null # TODO : handle logs      
    volumes:
      - ./data/mongo:/data/db:rw
    restart: always

  api:
    build: ./api
    depends_on:
      - database
    ports: 
      - '3030:3030'
    volumes: 
      - ./api:/srv/api
      - api_node_modules:/srv/api/node_modules
    command: node src/
#    tty: true

  frontend:
    build: ./frontend
    ports: 
      - '8080:8080'
    volumes: 
      - ./frontend/:/srv/app
      - frontend_node_modules:/srv/app/node_modules
    restart: 'no'
    command: quasar dev
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  frontend_node_modules:
  api_node_modules:
